### PR TITLE
specify hostpath in sync-repeat command args

### PR DESCRIPTION
**Pull request by leemhenson**
hey there.

```sync-repeat``` was not working for me, and I tracked it down to the unison command args. I don't know if ```hosts``` has a special meaning in unison, but in my testing it just treated it as a local path and synced everything from the remote host into a local ```./hosts``` directory that it created. If I change it to the host path from my Vagrantfile config, everything works as expected.

### CODE REVIEW

**Comment by dmatora** [comment]
can you also fix it on line 256?

**Comment by leemhenson** [comment]
Yeeeeeeaaaaaah. 



I totally WAS going to do what you asked but then I couldn't help myself. So how about this pull request instead that totally:

* changes ALL OF THE CODE
* introduces NEW FEATURES
* fixes OLD BUGS
* enhancerizes READABILITEEZ

:helicopter: 

"New features" is just the repeat arg config mentioned earlier.
"Old bugs" is the host path bugs mentioned earlier, but also the bug where the cleanup command deletes a directory on your host machine if it's named the same as the shared directory on the guest. :dancer: 

Extra good news though, I TOTALLY REMOVED WHITESPACE IN A SEPARATE COMMIT!

**Comment by dmatora** [comment]
Well, without tests implemented, changing that huge amount of code just can't avoid producing issues, and i don't like the idea of destroying master. On the other hand, that amount of effort definitely deserves encouragement. So screw everyone, if your code breaks everything :)

**Comment by dmatora** [comment]
You've spent so much effort on the project.
It would be way more useful to spend it on finishing event based synchronization.

Vagrant delivers filesystem changes notification from both host and guest, it should not take a lot of effort to utilize it. Currently this plugin is CPU hog. How do you feel about fixing that?

**Comment by leemhenson** [comment]
It already works if you do this on Mac OSX:

```
pip install pyobjc
brew install https://raw.githubusercontent.com/Homebrew/homebrew/924387b7b3ca3e2168c5302c791f354b1e4b92f6/Library/Formula/objective-caml.rb
wget http://www.seas.upenn.edu/~bcpierce/unison//download/releases/stable/unison-2.48.3.tar.gz
tar xf unison-2.48.3.tar.gz
cd unison-2.48.3
make ./mkProjectInfo
make UISTYLE=text
ln -s `pwd`/unison /usr/local/bin/
ln -s `pwd`/fsmonitor.py /usr/local/bin/
```

and this on a Ubuntu guest:

```
apt-get install emacs ocaml python-pyinotify
curl -L --silent http://www.seas.upenn.edu/~bcpierce/unison//download/releases/stable/unison-2.48.3.tar.gz > /tmp/unison-2.48.3.tar.gz
cd /tmp
tar xf unison-2.48.3.tar.gz
cd unison-2.48.3
make UISTYLE=text
cp unison /usr/local/bin
cp fsmonitor.py /usr/local/bin
sysctl -n -w fs.inotify.max_user_watches=1048576
```

Then it will use fs events rather than polling. Still not lighting fast for large projects, but better than polling.

**Comment by dmatora** [comment]
let me test it

what about http://mrdavidlaing/vagrant-unison/#7 ?

**Comment by leemhenson** [comment]
I don't see that.

**Comment by dmatora** [comment]
did you remove unison config from vagrantfile?

**Comment by leemhenson** [comment]
I don't really follow? This is my vagrantfile config:

``` ruby
config.sync.host_folder = SHARED_HOST_DIRECTORY
config.sync.guest_folder = SHARED_GUEST_DIRECTORY
config.sync.ignore = "Name {.git,*.log}"
config.sync.repeat = 'watch'
```

**Comment by dmatora** [comment]
yeah, that's config for unison - clean it
try a project that does not use unison (like project that is using amazon ec2 or digital ocean as provider)
vagrant up/provision will fail unless you uninstall vagrant-unison

**Comment by leemhenson** [comment]
Oh, I've no idea then. I only use vagrant for this one project.

**Pull request merged**
